const platforms = {
  nintendo: [
    "SNES",
    "Game Boy Advance",
    "NES",
    "Wii",
    "Nintendo Switch",
    "Game Boy",
    "Nintendo 3DS",
    "Wii U",
    "Nintendo DS",
    "New Nintendo 3DS",
    "Nintendo DSi",
    "Game Boy Color",
    "GameCube",
    "N64",
  ],
  sega: [
    "SEGA CD",
    "SEGA Saturn",
    "Genesis",
    "Game Gear",
    "SEGA Master System",
    "SEGA 32X",
    "Dreamcast",
    "SG-1000",
  ],
  playstation: [
    "PlayStation",
    "PlayStation 2",
    "PlayStation 3",
    "PlayStation 4",
    "PlayStation 5",
    "PSP",
    "PS Vita",
    "PlayStation Now",
  ],
  xbox: ["Xbox", "Xbox 360", "Xbox One", "Xbox Series", "Xbox Cloud Gaming"],
};

export default platforms;
